### ISSUE TITLE
Error "ERR_UNKNOWN_URL_SCHEME" when loading Angular Bundles

### ISSUE THREAD

**Issue by mainawycliffe** [lacolaco/ngx-web-bundles#1]
Not sure what I am doing wrong on my experiment with this builder, but I am getting the error "ERR_UNKNOWN_URL_SCHEME" for all Angular build artifacts. I have built your test project and that works well. I have a link to the repo [here](https://github.com/mainawycliffe/ngx-web-bundler-experiment).
![Annotation 2019-11-13 230705](https://user-images.githubusercontent.com/12270550/68800193-b323f680-066a-11ea-8f1f-3ddd0b00b5c5.png)

**Comment by lacolaco** [comment]
@mainawycliffe I guess your index.html includes `<base href>` tag. Currently Chrome doesn't support base tag with Web Bundles.

**Comment by mainawycliffe** [comment]
You are right, removing the <base href> solve the problem. Also setting as the `primaryURL` works as well, this is great since it can be done with a build environment configuration. This package is amazing, maybe we should update the read me to reflect that.

**Comment by lacolaco** [comment]
@mainawycliffe thank you for the feedback! It makes sense. I'll do that! 👍

**Comment by mainawycliffe** [comment]
I have updated my repo accordingly, thank you for this amazing package.
